(function(g){var window=this;var Z4=function(a){var b={format:a.o,languageCode:a.l,languageName:a.C,displayName:g.vH(a),kind:a.A,name:a.B,id:a.Ba,is_servable:a.L,is_translateable:a.F,vss_id:a.D};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},$4=function(a){return a.g?a.g.languageCode:a.l},gwa=function(a,b){var c=new g.uH;
c.l=a.l;c.C=a.C;c.B=a.B;c.A=a.A;c.F=a.F;c.D=a.D;c.H=a.H;c.g=b;return c},hwa=function(a){a=g.ld(window.document,"track",void 0,a.g);
for(var b=0;b<a.length;b++)g.Ed(a[b])},iwa=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},a5=function(a){if(!jwa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(kwa,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},b5=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.dP.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.B=f;this.l=k},c5=function(a,b,c,d,e){g.dP.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},e5=function(a){a=void 0===a?{}:a;
var b="_"+d5++;return new c5(0,0x8000000000000,0,b,a)},f5=function(a,b,c,d,e,f){var k={};
g.Ea(k,b);g.Ea(k,a.params);g.Ea(k,c);var l={};g.Ea(l,b.rb);a.params.rb&&g.Ea(l,a.params.rb);g.Ea(l,c.rb);k.rb=l;g.Y.call(this,{G:"div",M:"caption-window",T:{id:"caption-window-"+a.id,dir:1==k.Zj?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{G:"span",M:"captions-text"}]});this.o=[];this.I=!1;this.D=a;this.C=[];this.F=[];this.va=e;this.na=f;this.B=null;this.W=.96*e;this.da=.96*f;this.l=k;this.ma=c;this.A=this.sa["captions-text"];this.fa=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.K=d/360*16;this.type=0;this.Y=this.K*lwa(l);a=new g.mF(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.qL,this);a.subscribe("dragmove",this.pL,this);a.subscribe("dragend",this.oL,this);this.ca=this.ba=0;a="";this.l.lk&&(a=a5(this.l.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.lk+")");b={"background-color":a,display:!1===this.l.isVisible?"none":"","text-align":mwa[this.l.textAlign]};this.fa&&(b["border-radius"]=a?this.Y/
8+"px":"");g.kh(this.element,b);switch(this.l.Rg){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},lwa=function(a){var b=1+.25*(a.bj||0);
if(0==a.offset||2==a.offset)b*=.8;return b},g5=function(a,b){var c={},d=b.background?b.background:a.l.rb.background;
if(null!=b.Ye||b.background){var e=null!=b.Ye?b.Ye:a.l.rb.Ye;d=a5(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.fa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Y/8+"px")}if(null!=b.bj||null!=b.offset)c["font-size"]=a.K*lwa(b)+"px";d=1;e=b.color||a.l.rb.color;if(b.color||null!=b.Fh)e=a5(e),d=null==b.Fh?a.l.rb.Fh:b.Fh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Sh;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.uw&&
(k=e=b.uw);var l=a.K/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.$D()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.rb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.ws&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.Gr&&(c.visibility="hidden");return c},nwa=function(a,b,c){a.I=a.I||!!c;
var d={};g.Ea(d,a.l.rb);g.Ea(d,c||b.l);g.Ea(d,a.ma.rb);c=a.C[0];if(c&&d.background==c.background&&d.Ye==c.Ye&&!!d.Gr==!!c.Gr&&d.Sh==c.Sh){var e;for(e=0;e<a.C.length;e++)if(iwa(d,a.C[e])){var f=a.F[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.yd("SPAN");g.kh(f,g5(a,e));a.F[0].appendChild(f);e=1}a.F.length=e;a.C.length=e}else a.F.length=0,a.C.length=0,f=g.yd("SPAN"),g.kh(f,g5(a,d)),a.A.appendChild(f);a.B&&a.B.parentNode!=f&&(g.Ed(a.B),f.appendChild(a.B));c=(k=g.v(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.o.length||!b.B){if(0<e||0!=a.o.length){var m=g.yd("BR");f.appendChild(m)}f.appendChild(g.zd("\u00a0"));a.B=g.zd("\u00a0");f.appendChild(a.B)}l&&(m=a.B,m.parentNode&&m.parentNode.insertBefore(k?g.zd(l):l,m))}a.C.push(d);a.F.push(f);a.o.push(b)},owa=function(){},i5=function(){this.A=this.l=this.mode=this.o=0;
this.B=new h5(this);this.C=new h5(this);this.g=[];this.clear()},qwa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Mm:a,
Nm:b,result:0};a=pwa[a];b=pwa[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{Mm:a,Nm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Mm:a,Nm:b,result:2};return{Mm:a,Nm:b,result:3}},swa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,rwa(a.B,b,c,d))},twa=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?swa(a,d.ow,d.pw,b):1==d.type&&a.o&496&&rwa(a.C,d.ow,d.pw,b)}a.g.length=0},j5=function(){this.g=0},k5=function(){this.l=this.o=this.g=0},l5=function(){this.timestamp=this.pe=0;
this.g=!1},m5=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new l5}this.g=this.l=this.Ec=0;this.style=new j5;this.B=a;this.A=0},n5=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.o[m][q];
if(0!=r.pe){0==c&&(c=m,d=q);n=String.fromCharCode(r.pe);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.pe||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.A(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.o[k][m],r=q.pe,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),t=q.timestamp,t<=e&&(e=t),l+=n,q.reset()),32==m||0==r)l&&b.A(c,d,e,f,l),e=f,l="",d=c=0},ywa=function(a,b){switch(a){case 0:return uwa[(b&127)-32];
case 1:return vwa[b&15];case 2:return wwa[b&31];case 3:return xwa[b&31]}return 0},o5=function(a){return a.o[a.Ec][a.l]},p5=function(a,b,c){2<=b&&1<a.l&&(--a.l,o5(a).pe=0);
var d=o5(a);d.timestamp=a.B.l+0;d.pe=ywa(b,c);32>a.l&&a.l++},zwa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].gn(a.o[c+e][f])},q5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},r5=function(a){a.Ec=0<a.g?a.g:1;
a.l=1;q5(a,0,15)},s5=function(a){this.A=a;
this.B=0;this.style=new j5;this.C=new m5(a);this.D=new m5(a);this.F=new m5(a);this.l=this.C;this.o=this.D;this.g=this.l},t5=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:n5(d,c),r5(a.l),r5(a.o),d.Ec=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(n5(d,c),q5(d,d.Ec-d.g,b)):d.Ec<b&&(b=d.g),d.g=b)},Awa=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},Bwa=function(a){a.style.set(4);
a.g=a.F;a.g.style=a.style;a.A.mode=1<<a.g.A},h5=function(a){this.l=a;
this.g=new k5;this.B=0;this.o=new s5(a);this.C=new s5(a);this.A=this.o},rwa=function(a,b,c,d){a.g.update();
b=qwa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Mm;c=b.Nm;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&p5(a,0,b),c&96&&p5(a,0,c),0!=b&&0!=c&&3==a.style.g&&n5(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.Ec;break;case 3:if(d!=c.Ec){if(d<c.g&&(d=c.g,d==c.Ec))break;var f=1+c.Ec-c.g,k=1+d-c.g;zwa(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));q5(c,b,e)}}c.Ec=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:p5(b.g,0,32);break a;case 48:57==c?(b=b.g,o5(b).pe=0,32>b.l&&b.l++):p5(b.g,1,c&15)}break;case 2:c&32&&p5(b.g,2,c&31);break;case 3:c&32&&p5(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Awa(b);break;case 33:b=
b.g;1<b.l&&(--b.l,o5(b).pe=0);break;case 36:b=b.g;d=o5(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:t5(b,2,d);break;case 38:t5(b,3,d);break;case 39:t5(b,4,d);break;case 40:p5(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.F;d.g=15;d.style.set(4);r5(d);Bwa(b);break;case 43:Bwa(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:n5(a,d)}q5(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Ec){++a.Ec;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.Ec<a.g&&(a.Ec=a.g));b=a.Ec-a.g+1;n5(a,d);zwa(a,b,b+1,a.g-1);q5(a,a.Ec,1)}break;case 46:q5(b.o,0,15);break;case 47:n5(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;Awa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},u5=function(){},v5=function(a){this.o=a;
this.l=null},Dwa=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Kr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");Cwa(d,e,k,b,f,a.firstChild,{},c)},Cwa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.ws=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");w5.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new b5(a,b,c,d,n.nodeValue,e||0<m,g.Wb(k)?void 0:k));else{var q={};g.Ea(q,k);Cwa(a,b,c,d,e||0<m,n,q,l)}}},x5=function(){this.o={};
this.l=null},y5=function(a){this.l={};
this.B={};this.C={};this.o="_"+d5++;this.A=a},z5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},A5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},B5=function(a,b){var c=z5(a,b);
if(void 0!=c)return c},C5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return w5.test(c),c},Ewa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ea(c,d?a.C[d]:a.A);d=B5(b,"mh");null!=d&&(c.Js=d);d=B5(b,"ju");null!=d&&(c.textAlign=d);d=B5(b,"pd");null!=d&&(c.Zj=d);d=C5(b,"wfc");null!=d&&(c.windowColor=d);d=z5(b,"wfo");void 0!=d&&(c.lk=d/255);return c},Fwa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ea(c,a.B[d]);d=B5(b,"ap");null!=d&&(c.Rg=d);d=z5(b,"cc");null!=d&&(c.cH=d);d=z5(b,"ah");null!=d&&(c.oi=d);d=z5(b,"rc");null!=d&&(c.Uo=d);d=z5(b,"av");null!=d&&(c.Li=d);return c},Gwa=function(a,b,c){var d={};
g.Ea(d,Fwa(a,b));g.Ea(d,Ewa(a,b));c?iwa(d,a.A)?(c=a.o,d=a.A):c="_"+d5++:c=b.getAttribute("id")||"0";a=z5(b,"t");b=z5(b,"d")||0x8000000000000;return new c5(a,b,0,c,d)},D5=function(a,b,c){this.D=c;
this.version=this.B=this.C=this.g=0;this.l=new window.DataView(a);this.o=[]},E5=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},Hwa=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},F5=function(a,b){this.o=a;
this.track="CC3"==b.C?4:0;this.l=new i5;this.l.o=1<<this.track},Iwa=function(a){if(!(a.g<a.l.byteLength))return!1;
var b=Hwa(a);b.toString(16);if(1380139777!=b)return!1;a.version=E5(a);if(1<a.version)return!1;E5(a);E5(a);E5(a);return!0},Jwa=function(){this.l=[];
this.g=[]},G5=function(a,b){return b?a.g.concat(a.l):a.g},H5=function(a,b){switch(b.A){case "asr":var c=a.l;
g.Ia(c,(0,g.z)(b.I,b))||c.push(b);break;default:c=a.g,g.Ia(c,(0,g.z)(b.I,b))||c.push(b)}},I5=function(){this.l=null},Kwa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.ws=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new b5(b,c,d,e.id,q.nodeValue,f||0<n,g.Wb(l)?void 0:l),m.push(q),e!=a.l&&e.l.push(q);else{var r={};g.Ea(r,l);Kwa(a,b,c,d,e,!0,q,r,m)}}},J5=function(a){var b=0;
a=g.ma(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},K5=function(a){g.M.call(this);
this.Ey=!!a;this.l=new Jwa;this.D=[];this.g=null},Mwa=function(a){var b={};
if(a=$4(a))b.lang=a,Lwa.test(a)&&(b.Zj=1);return b},Nwa=function(a,b,c,d,e){d=d||0;
e=e||0;if(g.v(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new I5),a.g.g(b,d);b=g.Kr(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new y5(Mwa(c)):a.g=new x5:a.g=new v5(Mwa(c)));return a.g.g(b,d)}try{if(g.v(b))var f=!1;else{var k=new D5(b,8,0);f=Iwa(k)}if(f)return a.g||(a.g=new F5(e,c)),a.g.g(b,d)}catch(l){g.wD(l)}return[]},L5=function(a){K5.call(this,a.Tm);
this.A=void 0;this.o=null;this.D=a.captionTranslationLanguages},M5=function(){this.sb=[]},N5=function(a,b,c,d,e,f){g.M.call(this);
this.C=b;this.A=new M5;this.g=null;this.D=d;this.I=f;this.l=this.o=null;this.K=c;this.B=e||!1;this.F=new g.Lt(this.Ry,1E3,this);g.N(this,this.F);this.H=new g.hF(this);g.N(this,this.H);this.H.O(b,"seekto",this.Dz);this.Dz(b.getCurrentTime());this.Ry()},Owa=function(a,b){var c=g.uJ(b,{}).Oa(),d={format:"RAW",
ed:(0,g.z)(a.dR,a),withCredentials:!0};a.B&&(d.responseType="arraybuffer");a.l=g.RD(c,d);a.o=b;c=a.A;d=a.o.ya[0].pa;var e=g.db(c.sb,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.sb[e-1]&&e<c.sb.length&&1==c.sb[e]-d?(g.Sa(c.sb,e),g.Sa(c.sb,e-1)):0<e&&1==d-c.sb[e-1]?c.sb[e-1]=d:e<c.sb.length&&1==c.sb[e]-d?c.sb[e]=d:(g.Za(c.sb,e,0,d),g.Za(c.sb,e+1,0,d)))},O5=function(a,b){K5.call(this);
this.A=a;this.B=b;this.o=null;this.C=!1},Pwa=function(a,b){if(b in a.A.g)return a.A.g[b];
if(g.TJ(a.A))for(var c in a.A.g){var d=a.A.g[c];if(d.info.mimeType.includes("vtt"))return d}return null},P5=function(a,b,c,d,e,f){f5.call(this,a,b,c,d,e,f);
this.type=1},Q5=function(a,b,c,d,e,f){f5.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=2;this.H=this.L=0;this.N=window.NaN;this.ka=null;this.X=new g.Lt(this.hR,433,this);g.N(this,this.X)},R5=function(a){if(!a.L){var b=g.yd("SPAN");
g.kh(b,g5(a,a.l.rb));a.A.appendChild(b);b.appendChild(g.zd("M"));var c=b.offsetHeight,d=g.yd("BR");b.appendChild(d);b.appendChild(g.zd("M"));a.L=b.offsetHeight-c;a.A.removeChild(b)}return a.L},S5=function(a,b,c,d){K5.call(this,d);
c=c||g.ID(a).hl||"";c=c.split("_").join("-");this.B=g.KD(a,{hl:c});this.A=b;this.C={};this.o=null},V5=function(a){g.tU.call(this,a);
g.rG({YTP_CLICK_FOR_SETTINGS:"Haz clic en $GEAR_ICON para ir a la configuraci\u00f3n",YTP_SAMPLE_SUBTITLES:"Los subt\u00edtulos tendr\u00e1n este aspecto"});this.o=g.W(a);this.A=a.ea();this.ka=g.TT(a);this.K=a;var b=null,c=g.TC("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.HC(c));this.ba=b;this.C={rb:{}};this.H={rb:{}};this.L=[];this.V={};this.Y={};this.N=!1;this.ma="1"==this.A.Wb.cc_auto_caps||"1"==this.o.Xc.cc_auto_caps;this.F="3"==this.o.A&&!!a.app.B&&!!a.app.B.g.textTracks;c=b=this.l=
this.B=this.D=this.I=this.X=this.fa=null;this.F||(b=new g.It(this.nD,void 0,this),g.N(this,b),c=new g.Lt(this.VS,2E3,this),g.N(this,c));this.ca=b;this.da=c;this.W=new g.hF(this);g.N(this,this.W);this.F||this.W.O(a,"resize",this.Fu);this.W.O(a,"onPlaybackAudioChange",this.iO);this.W.O(a,"crn_captions",this.UK,this);this.W.O(a,"crx_captions",this.VK,this);T5(this,U5(this,"display-settings")||{})},Qwa=function(a){if(a.A.captionTracks.length)var b=a.g.vh().kw;
if("FORCED_ON"==b||1==a.o.Vg||1==a.A.Vg||"alwayson"==g.tN(a.A,"yt:cc"))return!0;if(2==a.o.Vg){var c=U5(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.tN(a.A,"yt:cc")},Rwa=function(a,b){if(a.B){var c=G5(a.B.l,b||a.ma);
if(a.D&&a.D.g)return a.D.g;for(var d=[a.A.Ug,a.o.Ug,g.tN(a.A,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if($4(c[f])==d[e])return c[f];return a.D&&a.D.Nq?a.D.Nq:c[0]||a.D&&a.D.Dk}return null},Swa=function(a,b){for(var c=a.K.app.B.g.textTracks,d=a.l.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},W5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.N=c);a.l=b;a.load(d)},Twa=function(a,b){var c=g.LY(a.ka,!0).height;
if(!c)return null;var d=a.ka.Sa();switch(null!=b.params.Js?b.params.Js:b.params.HT?2:1<b.l.length?1:0){case 1:return new P5(b,a.C,a.H,c,d.width,d.height);case 2:return new Q5(b,a.C,a.H,c,d.width,d.height);default:return new f5(b,a.C,a.H,c,d.width,d.height)}},T5=function(a,b,c){var d=X5.rb;
a.C={};g.Ea(a.C,X5);a.C.rb={};g.Ea(a.C.rb,d);a.H={rb:{}};var e=b.backgroundOverride?a.H:a.C,f=b.background||d.background;w5.test(f);e.rb.background=f;e=b.colorOverride?a.H:a.C;f=b.color||d.color;w5.test(f);e.rb.color=f;e=b.windowColorOverride?a.H:a.C;f=b.windowColor||X5.windowColor;w5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.H:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ye);e.rb.Ye=f;e=b.fontSizeIncrementOverride?a.H:a.C;f=b.fontSizeIncrement;null==f&&(f=d.bj);e.rb.bj=f;e=b.textOpacityOverride?
a.H:a.C;f=b.textOpacity;null==f&&(f=d.Fh);e.rb.Fh=f;e=b.windowOpacityOverride?a.H:a.C;f=b.windowOpacity;null==f&&(f=X5.lk);e.lk=f;e=b.charEdgeStyleOverride?a.H:a.C;f=b.charEdgeStyle;null==f&&(f=d.Sh);e.rb.Sh=f;e=b.fontFamilyOverride?a.H:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.rb.fontFamily=f;a.loaded&&a.Fu();c&&Y5(a,"display-settings",b)},Vwa=function(a,b){if(b&&!a.I){var c=e5({Zj:0,
lang:"es"});a.I=[c,new b5(c.start,c.end-c.start,0,c.id,g.U("YTP_SAMPLE_SUBTITLES"))];g.gU(a.g,a.I)}else!b&&a.I&&(Uwa(a,a.I),a.I=null)},Uwa=function(a,b){g.iU(a.g,b);
(0,g.C)(b,function(a){g.Ta(this.L,a)},a);
a.ca.Lk()},Wwa=function(a,b){return a&&g.v(a)&&w5.test(a)?a:b},Xwa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},Zwa=function(a,b){if(a&&g.v(a)){var c=Ywa.indexOf(a);
return-1!=c?c:b}return b},axa=function(a,b){if(a&&g.v(a)){var c=$wa.indexOf(a);
return-1!=c?c:b}return b},bxa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?g.Yc(a,-2,4):b},U5=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},Y5=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.AH.prototype.Hn=g.ca(4,function(a){return(a=this.Xh(a))?a.l:0});
g.JJ.prototype.Hn=g.ca(3,function(){return 0});
g.uH.prototype.I=g.ca(2,function(a){return a?this.toString()==a.toString():!1});
var Lwa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,kwa=/#(.)(.)(.)/,jwa=/^#(?:[0-9a-f]{3}){1,2}$/i,w5=/^#(?:[0-9a-f]{3}){1,2}$/i,$wa="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),Ywa=["none","raised","depressed","uniform","dropShadow"];var mwa=["left","right","center"];var X5={windowColor:"#080808",lk:0,textAlign:2,Rg:7,oi:50,Li:100,rb:{background:"#080808",Ye:.75,Sh:0,color:"#fff",fontFamily:4,bj:0,Fh:1,offset:1}};g.p(b5,g.dP);g.p(c5,g.dP);var d5=0;g.p(f5,g.Y);g.h=f5.prototype;g.h.qL=function(a,b){var c=g.Ah(this.element,this.element.parentElement);this.ba=a-c.x;this.ca=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.pL=function(a,b){var c=g.Dh(this.element),d=a-this.ba-.02*this.va,e=b-this.ca-.02*this.na,f=(d+c.width/2)/this.W*3;f=Math.floor(g.Yc(f,0,2));var k=(e+c.height/2)/this.da*3;k=Math.floor(g.Yc(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.W;d=100*g.Yc(d,0,1);c=(e+k/2*c.height)/this.da;c=100*g.Yc(c,0,1);this.D.params.Rg=l;this.D.params.Li=c;this.D.params.oi=d;this.l.Rg=l;this.l.Li=c;this.l.oi=d;this.gC()};
g.h.oL=function(){g.gq(this.element,"ytp-dragging")};
g.h.gC=function(){this.Ii(this.o)};
g.h.Sb=function(){return this.type};
g.h.Ii=function(a){var b=Math.min(this.Ax(),this.W),c=this.zx();g.kh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.mq(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.l.oi+2,e=this.l.Rg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.l.Li+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.kh(this.element,a)};
g.h.mq=function(a){var b;for(b=0;b<a.length&&a[b]==this.o[b];b++);if(this.I||this.o.length>b)b=0,this.I=!1,this.o=[],this.C=[],this.F=[],this.B=null,g.Cd(this.A);for(;b<a.length;b++)nwa(this,a[b])};
g.h.Ax=function(){return 0};
g.h.zx=function(){return 0};
g.h.toString=function(){return g.Y.prototype.toString.call(this)};owa.prototype.A=function(){};i5.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
i5.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var pwa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];j5.prototype.set=function(a){this.g=a};
j5.prototype.get=function(){return this.g};
k5.prototype.clear=function(){this.g=0};
k5.prototype.update=function(){this.g=2==this.g?1:0};
k5.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
l5.prototype.gn=function(a){this.pe=a.pe;this.timestamp=a.timestamp;this.g=a.g};
l5.prototype.reset=function(){this.timestamp=this.pe=0;this.g=!1};
m5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.pe?a+"_":a+String.fromCharCode(d.pe)}a+="\n"}return a};
m5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.Ec=1};
var uwa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],vwa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],wwa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],xwa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];s5.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.D;this.g=this.l;var c=(a<<2)+(b<<1)+0;this.C.reset(c);this.D.reset(c);this.F.reset((a<<2)+(b<<1)+1)};
h5.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};u5.prototype.reset=function(){};g.p(v5,u5);v5.prototype.g=function(a){var b=[];this.l||(this.l=e5(this.o),b.push(this.l));a=g.ma(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())Dwa(c.value,this.l.id,b);return b};g.p(x5,u5);
x5.prototype.g=function(a){var b=[];this.l||(this.l=e5(),this.o[this.l.id]=this.l,b.push(this.l));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c;var f=this.o[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||
(f=e5());var k={};f&&(g.Ea(k,f.params),f=f.params.rb)&&(k.rb={},g.Ea(k.rb,f));e.getAttribute("rc")&&(k.Uo=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.cH=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Rg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.oi=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Li=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Zj=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Zj=0));e.getAttribute("bc")&&(k.rb||(k.rb={}),k.rb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.rb||(k.rb={}),k.rb.Ye=(0,window.parseInt)(e.getAttribute("bo"),10)/100);if(e.getAttribute("fc")){k.rb||(k.rb={});var l=k.rb;f=e.getAttribute("fc");l.color=f}e.getAttribute("sd")&&(k.HT=(0,window.parseInt)(e.getAttribute("sd"),
10));f=(0,window.parseInt)(e.getAttribute("d"),10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new c5(c,f,0,e,k)}else c=null}this.o[d]=c;b.push(c);break;case "text":for(d=[],Dwa(a,this.l.id,d),d=g.ma(d),c=d.next();!c.done;c=d.next())c=c.value,this.o[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(y5,u5);
y5.prototype.g=function(a){a.firstChild.getAttribute("format");a=g.ma(a.firstChild.childNodes);for(var b=a.next();!b.done;b=a.next())if(b=b.value,1==b.nodeType)switch(b.tagName){case "head":var c=b;break;case "body":var d=b}if(c)for(c=g.ma(c.childNodes),a=c.next();!a.done;a=c.next())if(a=a.value,1==a.nodeType)switch(a.tagName){case "pen":b=a.getAttribute("id");var e=this.l,f={},k=a.getAttribute("p");k&&g.Ea(f,this.l[k]);k=A5(a,"b");null!=k&&(f.bold=k);k=A5(a,"i");null!=k&&(f.ws=k);k=A5(a,"u");null!=
k&&(f.underline=k);k=B5(a,"et");null!=k&&(f.Sh=k);k=B5(a,"of");null!=k&&(f.offset=k);k=C5(a,"bc");null!=k&&(f.background=k);k=C5(a,"ec");null!=k&&(f.uw=k);k=C5(a,"fc");null!=k&&(f.color=k);k=B5(a,"fs");void 0!=k&&0!=k&&(f.fontFamily=k);k=z5(a,"sz");void 0!=k&&(f.bj=k/100-1);k=z5(a,"bo");void 0!=k&&(f.Ye=k/255);a=z5(a,"fo");void 0!=a&&(f.Fh=a/255);e[b]=f;break;case "ws":b=a.getAttribute("id");this.C[b]=Ewa(this,a);break;case "wp":b=a.getAttribute("id"),this.B[b]=Fwa(this,a)}c=[];if(d)for(a={},b=void 0,
d=g.ma(d.childNodes),e=d.next();!e.done;e=d.next())if(e=e.value,1==e.nodeType)switch(e.tagName){case "w":var l=Gwa(this,e,!1);(e=a[l.id])&&e.end>l.start&&(e.end=l.start);a[l.id]=l;c.push(l);break;case "p":var m=b,n=ue;f=[];k=e.getAttribute("w")||this.o;var q=!!A5(e,"a"),r=z5(e,"t")||0,t=z5(e,"d")||5E3;!n&&!q&&m&&m.windowId==k&&m.end>r&&(m.end=r);m=q?6:5;n=this.l[e.getAttribute("p")];for(var B=e.childNodes,G=0;G<B.length;G++){var I=B[G];0<G&&(q=!0);var X=void 0;1==I.nodeType&&(X=I);if(X&&"s"==X.tagName){var ia=
X;I=r;X=t;var ab=k,La=q,Na=m,li=ia.textContent?ia.textContent:"",zb=this.l[ia.getAttribute("p")];ia=z5(ia,"t")||0;I=new b5(I+ia,X-ia,Na,ab,li,La,zb)}else I=new b5(r,t,m,k,I.textContent||"",q,n);f.push(I)}b&&"\n"==b.text&&(b.text="");if(0<f.length){b=f[f.length-1];var ue=null!=e.getAttribute("d");f[0].windowId==this.o&&(l=Gwa(this,e,!0),c.push(l));e=g.ma(f);for(f=e.next();!f.done;f=e.next())f=f.value,f.windowId=l.id,l.l.push(f),c.push(f)}}return c};g.p(D5,owa);D5.prototype.A=function(a,b,c,d,e){if(c<d){var f="_"+d5++;c=c/1E3-this.D;d=d/1E3-this.D;a=new c5(c,d-c,5,f,{textAlign:0,Rg:0,oi:2.5*b,Li:5.33*a});e=new b5(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.p(F5,u5);F5.prototype.g=function(a){a=new D5(a,a.byteLength,this.o);if(Iwa(a)){for(;a.g<a.l.byteLength;)for(0==a.version&&(a.C=Hwa(a)*(1E3/45)),a.B=E5(a);0<a.B;a.B--){var b=E5(a),c=E5(a),d=E5(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.l,b.g.push({time:a.C,type:this.track,ow:c,pw:d,order:b.g.length}))}twa(this.l,a);return a.o}return[]};
F5.prototype.reset=function(){this.l.clear()};g.p(I5,u5);
I5.prototype.g=function(a,b){for(var c=[],d=a.split(cxa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!dxa.test(f)){var l=Z5.exec(f);if(l&&3<=l.length){var m=J5(l[1]);l=J5(l[2])-m;m+=k;f=f.substring(Z5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");Z5.lastIndex=0;var n=f;f={};this.l||(this.l=e5({Js:0}),c.push(this.l));var q=this.l;k=5;if(0>n.indexOf("<")&&0>n.indexOf("&"))c.push(new b5(m,l,k,q.id,n,!1,g.Wb(f)?void 0:f));else{n=n.split(exa);1!=n.length&&(k=6,q="_"+fxa++,q=new c5(m,l,k,q,{}),c.push(q));
for(var r=m,t=0;t<n.length;t++){var B=n[t];if(0==t%2){var G=g.Kr("<html>"+B+"</html>");if(G.getElementsByTagName("parsererror").length){var I=G.createElement("span");I.appendChild(G.createTextNode(B))}else I=G.firstChild;Kwa(this,r,l-(r-m),k,q,0<t,I,f,c)}else r=J5(B)}}}Z5.lastIndex=0}}return c};
var fxa=0,dxa=/^NOTE/,cxa=/(?:\r\n|\r|\n){2,}/,Z5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),exa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(K5,g.M);K5.prototype.trackCount=function(){return G5(this.l,!0).length};
K5.prototype.Fd=function(){this.g=null};
K5.prototype.U=function(){g.M.prototype.U.call(this);this.Fd()};
K5.prototype.SB=function(){return!1};g.p(L5,K5);g.h=L5.prototype;g.h.Ds=function(a,b){var c=this.Jk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Fd();this.o=g.RD(c,{format:"RAW",Ib:d,withCredentials:!0})};
g.h.Es=function(a,b,c,d){this.A=c;if(d)for(b=g.ma(d.captionTracks),c=b.next();!c.done;c=b.next())H5(this.l,c.value);a()};
g.h.Jk=function(a){var b=a.Oa(),c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.g&&(c.tlang=a.g.languageCode);return g.KD(b,c)};
g.h.Fd=function(){K5.prototype.Fd.call(this);this.o&&this.o.abort()};
g.h.U=function(){this.Fd();K5.prototype.U.call(this)};M5.prototype.contains=function(a){a=g.db(this.sb,a);return 0<=a||0>a&&1==(-a-1)%2};
M5.prototype.length=function(){return this.sb.length/2};g.p(N5,g.M);g.h=N5.prototype;g.h.U=function(){g.M.prototype.U.call(this);this.l&&this.l.abort()};
g.h.Dz=function(a){var b=this.g;this.g=g.Ga(this.K.eh(a).ya);b!=this.g&&this.I&&this.I()};
g.h.reset=function(){this.A=new M5;this.l&&(this.l.abort(),this.l=null)};
g.h.Ry=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.ti(a);!a||this.l||this.g&&30<this.g.startTime-this.C.getCurrentTime()||(a=this.g,a=a.g.dl(a),!g.W(this.C).experiments.g("disable_captions_unknown_requests")&&!a.ya[0].duration)||(this.A.contains(a.ya[0].pa)||Owa(this,a),this.g=g.Ga(a.ya));this.F.start()};
g.h.dR=function(a){var b=!(this.B?a.response:a.responseText)||400<=a.status;if(!g.W(this.C).experiments.g("disable_captions_redirects_redux")){var c=g.OJ(a);if(c){a=g.uJ(this.o,{});b=this.o;g.sJ(b.g,a,c);b.requestId=a.get("req_id");Owa(this,this.o);return}}b||null===this.D||(this.B?this.D(a.response,1E3*this.o.ya[0].startTime):this.D(a.responseText,1E3*this.o.ya[0].startTime));this.l=this.o=null};g.p(O5,K5);g.h=O5.prototype;g.h.Ds=function(a,b){this.Fd();var c=Pwa(this,a.l);if(c){var d=1E3*c.index.Hn(c.index.vg()),e=g.W(this.B).Wa;this.o=new N5(new g.bJ,this.B,c,function(c,e){b(c,a,e,d)},e,(0,g.z)(function(){e&&(this.o&&this.o.reset(),this.g&&this.g.reset(),this.C=!0)},this))}};
g.h.SB=function(){var a=this.C;this.C=!1;return a};
g.h.Es=function(a){g.W(this.B).Wa?(H5(this.l,new g.uH({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),H5(this.l,new g.uH({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):H5(this.l,new g.uH({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.Fd=function(){K5.prototype.Fd.call(this);this.o&&(this.o.dispose(),this.o=null)};
g.h.Jk=function(){return""};
g.h.U=function(){this.Fd();K5.prototype.U.call(this)};g.p(P5,f5);P5.prototype.mq=function(a){var b=this.D.l;f5.prototype.mq.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Ea(d,c.l);g.Ea(d,gxa);var e=c.l;var f=d}nwa(this,c,d)}};
var gxa={Gr:!0};g.p(Q5,f5);g.h=Q5.prototype;g.h.gC=function(){g.Nt(this.X)};
g.h.hR=function(){g.gq(this.element,"ytp-rollup-mode");this.Ii(this.ka,!0)};
g.h.Ax=function(){return this.H};
g.h.zx=function(){return this.D.params.Uo*R5(this)};
g.h.Ii=function(a,b){this.ka=a;if(R5(this)){for(var c=0,d=0;d<this.o.length&&c<a.length;d++)this.o[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.o.concat(a.slice(c)));c=this.H;this.H=0;f5.prototype.Ii.call(this,a);this.H=Math.max(c,this.A.offsetWidth+1);c=this.D.params.Uo*R5(this)-this.A.offsetHeight;c!=this.N&&(b||(0,window.isNaN)(this.N)||(g.S(this.element,"ytp-rollup-mode"),g.Mt(this.X)),g.kh(this.A,"transform",c?"translateY("+c+"px)":""),this.N=c);f5.prototype.Ii.call(this,a)}else f5.prototype.Ii.call(this,
a)};g.p(S5,K5);g.h=S5.prototype;g.h.Ds=function(a,b){var c=this.Jk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Fd();this.o=g.RD(c,{format:"RAW",Ib:d,withCredentials:!0})};
g.h.Es=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.Ey&&(b.asrs=1);d=g.KD(d,b);b=(0,g.z)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.l,e=g.ma(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),t=m.getAttribute("kind"),B=m.getAttribute("id"),G="true"==m.getAttribute("cantran");
m=m.getAttribute("vss_id");H5(d,new g.uH({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:t,id:B,is_servable:!0,is_translateable:G,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),l={languageCode:l,languageName:n,languageOriginal:q,id:r},this.C[l.languageCode]=l.languageName,this.D.push(new g.tH(l))}a()},this);
this.Fd();this.o=g.RD(d,{format:"RAW",Ib:b,withCredentials:!0})};
g.h.Jk=function(a){var b=this.B,c={v:this.A,type:"track",lang:a.l,name:a.B,kind:a.A,fmt:a.o};a.g&&(c.tlang=$4(a));return b=g.KD(b,c)};
g.h.Fd=function(){K5.prototype.Fd.call(this);this.o&&this.o.abort()};
g.h.U=function(){this.Fd();K5.prototype.U.call(this)};g.p(V5,g.tU);g.h=V5.prototype;g.h.U=function(){if(this.F){var a=this.K.app.B;a&&hwa(a)}else Vwa(this,!1);g.tU.prototype.U.call(this)};
g.h.vz=function(){return this.F?!this.A.ua:this.A.captionTracks.length&&this.g.vh().Dk?!0:Qwa(this)};
g.h.load=function(a){g.tU.prototype.load.call(this);this.D=this.g.vh();if(this.B||a)this.l?(this.F&&!this.o.experiments.g("disable_native_caption_api")?Swa(this,!0):a?this.BB(a,this.l):3!=this.g.Qa()&&this.B.Ds(this.l,(0,g.z)(this.BB,this)),this.g.ra("captionschanged",Z4(this.l))):this.g.ra("onCaptionsTrackListChanged");else{var b;a=this.A;a.ua||g.W(this.K).Wa&&null!=a.oa&&null!=a.oa.g.rawcc?b=new O5(this.A.oa,this.g):this.A.captionTracks.length?b=new L5(this.A):b=new S5(this.A.Um,this.A.videoId,
this.A.Ug||this.o.Ug||g.tN(this.A,"yt:cc_default_lang")||this.o.Pa,this.A.Tm);this.B=b;b.Es((0,g.z)(this.JR,this),!0,this.F?"vtt":void 0,this.g.vh())}};
g.h.unload=function(){this.F?this.o.experiments.g("disable_native_caption_api")?hwa(this.K.app.B):this.l&&Swa(this,!1):(this.da&&g.Ot(this.da),g.jU(this.g,"captions"),this.L=[],this.B&&this.B.Fd(),this.I&&g.gU(this.g,this.I),this.Fu());g.tU.prototype.unload.call(this);var a=g.RT(this.g.app);a&&a.C&&g.vO(a.C.o);this.g.ra("captionschanged",{})};
g.h.JR=function(){if(this.N||Qwa(this))var a=Rwa(this,this.N);if(this.F){for(var b=G5(this.B.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.vH(e),srclang:$4(e),src:this.B.Jk(e),id:e.toString()};e==a&&(f["default"]=1);c.push(g.K("TRACK",f))}a=this.K.app.B;for(b=0;b<c.length;b++)a.g.appendChild(c[b]);(c=this.K.app.B.g)&&c.textTracks&&c.textTracks.addEventListener&&!this.o.experiments.g("disable_native_caption_api")&&this.W.O(c.textTracks,"change",this.KR)}else!this.l&&a&&W5(this,
a),this.g.ra("onCaptionsTrackListChanged"),this.g.ra("onApiChange")};
g.h.KR=function(){for(var a=this.K.app.B.g.textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=G5(this.B.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.l:null)!=b&&W5(this,b,!0)};
g.h.PT=function(){this.o.experiments.g("disable_native_caption_api")?this.loaded&&!this.F&&this.unload():!this.l&&this.F||this.unload()};
g.h.BB=function(a,b,c,d){if(a){this.B.SB()&&(this.L=[],g.jU(this.K,"captions"),this.ca.Lk());a=Nwa(this.B,a,b,c,d);g.gU(this.g,a);if(this.N&&(a={trackName:b.B,trackKind:b.A,trackLangCode:$4(b)},b.g&&(a.fromLangCode=b.l),g.aU(this.g,"cc",a),this.l!=(this.D&&this.D.Dk))){!this.N||g.xL(this.o)||g.ML(this.o)||(g.Ot(this.da),b=e5({Rg:0,oi:5,Li:5,Uo:2,textAlign:0,Zj:0,lang:"es"}),this.X=[b],a=g.U("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON"),this.fa||(c=new g.wU(g.jV()),g.N(this,c),this.fa=c.element),c=
b.end-b.start,(d=g.vH(this.l))&&this.X.push(new b5(b.start,c,0,b.id,d)),this.X.push(new b5(b.start,c,0,b.id,a[0]),new b5(b.start,c,0,b.id,this.fa,!0),new b5(b.start,c,0,b.id,a[1],!0)),g.gU(this.g,this.X),g.Mt(this.da));if(this.N||g.xL(this.o))Y5(this,"module-enabled",!0),this.D&&(this.D.g=this.l);(b=g.RT(this.g.app))&&b.C&&g.vO(b.C.o)}this.N=!1}};
g.h.UK=function(a){this.L.push(a);this.ca.Lk()};
g.h.VK=function(a){g.Ta(this.L,a);!this.o.experiments.g("disable_remove_displayed_close_caption_cue")&&this.o.Wa&&g.iU(this.g,[a]);this.ca.Lk()};
g.h.DS=function(a){if(a instanceof c5){var b=this.V[a.id];b&&b.D!=a&&(b.dispose(),delete this.V[a.id],b=null);b||(b=Twa(this,a))&&(this.V[a.id]=b)}else b=a.windowId,this.Y[b]||(this.Y[b]=[]),this.Y[b].push(a)};
g.h.VS=function(){Uwa(this,this.X);this.X=null};
g.h.nD=function(){this.ca.stop();g.Xb(this.Y);this.L.sort(g.fP);var a=this.L;if(this.I){var b=(0,g.Gd)(a,function(a){return-1==this.I.indexOf(a)},this);
b.length&&(a=b)}(0,g.C)(a,this.DS,this);g.Kb(this.V,function(a,b){this.Y[b]?(a.element.parentNode||g.nU(this.g,a.element,4),a.Ii(this.Y[b])):(a.dispose(),delete this.V[b])},this)};
g.h.fC=function(){T5(this,{},!0)};
g.h.jr=function(){var a=X5.rb;a={background:a.background,backgroundOpacity:a.Ye,charEdgeStyle:a.Sh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.bj,textOpacity:a.Fh,windowColor:X5.windowColor,windowOpacity:X5.lk};var b=U5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Iu=function(a,b){var c={};g.Ea(c,U5(this,"display-settings"));g.Ea(c,a);T5(this,c,b);this.g.R("captionssettingschanged")};
g.h.Fu=function(){!this.F&&this.loaded&&(g.Kb(this.V,function(a,b){a.dispose();delete this.V[b]},this),this.nD())};
g.h.Ss=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Yc(b,-2,4);this.Iu({fontSizeIncrement:c});return c;case "reload":b&&!this.F&&W5(this,this.l,!0);break;case "stickyLoading":void 0!=b&&this.o.Fb&&Y5(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.F)break;if(!g.Aa(b))break;if(g.Wb(b)){W5(this,null,!0);break}for(var d=G5(this.B.l,!0),e=0;e<d.length;e++){var f=d[e];f.l!=b.languageCode||c&&f.C!=b.languageName||(c=b.translationLanguage?gwa(f,
b.translationLanguage):f)}!c||c==this.l&&this.loaded||W5(this,c,!0)}else return this.loaded&&this.l&&this.l!=(this.D&&this.D.Dk)?Z4(this.l):{};return"";case "tracklist":return this.B?(0,g.H)(G5(this.B.l,!(!b||!b.includeAsr)),function(a){return Z4(a)}):[];
case "translationLanguages":return this.B?this.B.D:[];case "displaySettings":c=this.jr();if(g.xL(this.o)&&b&&g.Aa(b))if(b.reset)this.fC();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=Wwa(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=Xwa(b[d],c[d]);break;case "charEdgeStyle":f[d]=Zwa(b[d],c[d]);break;case "fontSizeIncrement":f[d]=bxa(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=axa(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.Iu(f,!0);c=this.jr()}c.fontFamilyOption=$wa[c.fontFamily];c.charEdgeStyle=Ywa[c.charEdgeStyle];return c;case "sampleSubtitles":this.F||void 0==b||Vwa(this,!!b);break;case "xmlTrack":b&&this.o.Fb&&(this.F||W5(this,new g.uH({languageName:b.name}),!1,b.xml))}};
g.h.SK=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.o.Fb&&a.push("stickyLoading","xmlTrack");return a};
g.h.TK=function(){var a=this.l;return a?{cc:a.D}:{}};
g.h.YC=function(){this.loaded&&this.l?(Y5(this,"module-enabled",!1),this.unload()):W5(this,this.l||Rwa(this,!0),!0)};
g.h.iO=function(){this.A.captionTracks.length&&(this.loaded&&this.unload(),this.vz()&&this.load())};g.BY.captions=V5;})(_yt_player);
